version: "3.9"

services:
  code-server:
    image: codercom/code-server:4.8.3
    ports:
      - "8443:8443"
    volumes:
      - ./workspace:/home/coder/project
      - ~/.config/code-server:/home/coder/.config/code-server
    command:
      - --auth
      - password
      - --user
      - admin:Password#123

  vault:
    image: hashicorp/vault:1.18
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    # volumes:
    #   - ./vault/file:/vault/file
    #   - ./vault/logs:/vault/logs
    environment:
      VAULT_ADDR: 'http://127.0.0.1:8200'
      VAULT_TOKEN: root
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_LOCAL_CONFIG: |
        ui = true
        disable_mlock = true
        storage "raft" {
          path = "/vault/file"
          node_id = "node_1"
        }
        listener "tcp" {
          address = "vault:8200"
        }
        api_addr = "http://valt:8201"
        cluster_addr = "http://vault:8201"
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio/data:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: Password#123
    command: server /data --console-address ":9001"
